import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import TopCards from '@/components/TopCards'
import { Providers } from './store/provider'
import jsonToObj from '@/utils/jsonToObj'
import ALL_DATA from '@/data/fuel-excel.json'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Sidebar>
            <main className="min-h-screen bg-gray-100">
              <Header />
              <TopCards />
              {children}
            </main>
          </Sidebar>
        </Providers>
      </body>
    </html>
  )
}

