import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import TopCards from '@/components/TopCards'
import { Providers } from './store/provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main >
            <div className='w-20'>
              <Sidebar />
            </div>
            <div className="w-[100%-5rem] ml-20 px-8 min-h-screen bg-gray-100">
              <Header />
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}

