import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import TopCards from '@/components/TopCards'
import { Providers } from './store/provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className='bg-gray-200 w-full h-screen grid grid-cols-[5rem_1fr] grid-rows-[5rem_1fr_1fr]'>
            <div className='col-span-1 row-span-3 '>
              <Sidebar />
            </div>
            <div className='col-span-1 row-span-1'>
              <Header />
            </div>
            <div className='col-span-1 row-span-2 wh-full'>
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  )
}

